# SWIN V2 Large Frozen v3 Configuration
# Model configuration
model:
  model_name_or_path: "microsoft/swinv2-large-patch4-window12-192-22k"
  config_name: null
  cache_dir: null
  model_revision: "main"
  image_processor_name: null
  token: null
  trust_remote_code: false
  ignore_mismatched_sizes: true

# Data configuration
data:
  dataset_name: null
  dataset_config_name: null
  data_file: null
  data_dir: null
  train_file: "/projectnb/herbdl/data/kaggle-herbaria/train.json"
  validation_file: "/projectnb/herbdl/data/kaggle-herbaria/val.json"
  image_column_name: "filepath"
  label_column_name: "scientificNameEncoded"
  max_seq_length: 15
  max_train_samples: null
  max_eval_samples: 500000
  overwrite_cache: false
  preprocessing_num_workers: null
  train_val_split: 0.2

# Training configuration
training:
  output_dir: "/projectnb/herbdl/workspaces/faridkar/herbdl/finetuning/output/SWIN/SWINV2_LARGE_UNFROZEN_50K"
  logging_dir: "/projectnb/herbdl/workspaces/faridkar/herbdl/finetuning/output/SWIN/SWINV2_LARGE_UNFROZEN_50K"
  do_train: true
  do_eval: true
  per_device_train_batch_size: 32
  per_device_eval_batch_size: 32
  learning_rate: 0.00003
  num_train_epochs: 35
  warmup_steps: 1000
  weight_decay: 0.01
  gradient_accumulation_steps: 1
  lr_scheduler_type: "cosine"
  lr_scheduler_kwargs:
    eta_min: 0.000001
  logging_strategy: "epoch"
  save_strategy: "epoch"
  save_total_limit: 5
  eval_strategy: "steps"
  eval_steps: 8964
  report_to: "wandb"
  bf16: true
  dataloader_num_workers: 8
  remove_unused_columns: false
  overwrite_output_dir: false
  seed: 42

# Custom configuration
custom:
  lr_type: "cosine"
  frozen: false
  frozen_type: "none"
  run_group: "SWINV2_Large"
  run_name: "SWINV2_Large_Unfrozen_50K"
  run_id: "swinv2_large_unfrozen_021626"

# WandB configuration
wandb:
  entity: "gardoslab"
  project: "herbdl"
  resume: "allow"
